app.py
from flask import Flask
from werkzeug.wsgi import DispatcherMiddleware

import config
from views import home, json_api


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    app.register_blueprint(home.bp)
    app.wsgi_app = DispatcherMiddleware(app.wsgi_app, {'/api': json_api})

    return app


app = create_app()

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=app.debug, threaded=True)

views/__init__.py
from .api import json_api

views/api.py
from flask import Flask, request, render_template
from flask.views import MethodView
from flask import jsonify
from werkzeug.wrappers import Response

from proxygetter.ext import proxydb


def jsonify_status(obj, status=200):
    result = jsonify(obj)
    result.status = status
    return result


# jsonify = jsonify_status


def create_app():
    app = Flask(__name__)
    return app


json_api = create_app()


class ProxyAPI(MethodView):

    def get(self):
        page = request.args.get('page', 1, type=int)
        page_size = request.args.get('page_size', 20, type=int)
        https = request.args.get('https', None)
        anonymous = request.args.get('anonymous', None)
        filter = {

        }
        if https == 'true':
            filter['https'] = True
        elif https == 'false':
            filter['https'] = False
        if anonymous == 'true':
            filter['anonymous'] = True
        elif anonymous == 'false':
            filter['anonymous'] = False
        start = page_size * (page - 1)
        end = page_size * page
        proxies = proxydb.find(filter)
        return jsonify({
            'proxies': list(proxies[start:end]),
            'total': proxies.count()
        })


# Local test CORS
@json_api.after_request
def after_request(response):
    response.headers.add('Access-Control-Allow-Origin', '*')
    response.headers.add(
        'Access-Control-Allow-Headers', 'Content-Type,Authorization')
    response.headers.add(
        'Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')
    return response


@json_api.errorhandler(500)
@json_api.errorhandler(404)
def error_handler(error):
    if hasattr(error, 'name'):
        msg = error.name
        code = error.code
    else:
        # msg = error.__name__
        msg = str(error)
        code = 500
    return jsonify({'message': msg}), code



json_api.add_url_rule('/proxy', view_func=ProxyAPI.as_view('proxy'))

views/home.py
from flask import Blueprint, render_template

bp = Blueprint('home', __name__)


@bp.route('/')
def index():
    return render_template('index.html')

templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>ProxyPool</title>
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
  <style>
  a {text-decoration: none;}
  </style>
</head>

<body>

<div id="app">
  <div id="navbar">
    <el-menu theme="dark" :default-active="activeIndex" class="el-menu-demo" mode="horizontal">
      <el-menu-item index="1">
        <a href="{{ url_for('home.index') }}">ProxyPool</a>
      </el-menu-item>
      <el-submenu index="2">
        <template slot="title">HTTPS</template>
        <el-menu-item index="2-1" @click="getProxies({'https':false})">HTTP</el-menu-item>
        <el-menu-item index="2-2" @click="getProxies({'https':true})">HTTPS</el-menu-item>
      </el-submenu>
      <el-submenu index="3">
        <template slot="title">Anonymous</template>
        <el-menu-item index="3-1" @click="getProxies({'anonymous':true})">Anonymous</el-menu-item>
        <el-menu-item index="3-2" @click="getProxies({'anonymous':false})">Transparent</el-menu-item>
      </el-submenu>
    </el-menu>
  </div>

  <div id="table">
    <el-row :gutter="20">
      <el-col :span="16" :offset="4">
        <div class="grid-content">
          <template>
            <el-table :data="tableData" border style="width: 100%">
              <el-table-column prop="ip" label="IP" width="240"></el-table-column>
              <el-table-column prop="port" label="PORT" width="90"></el-table-column>
              <el-table-column prop="https" label="HTTPS" width="90">
                <template slot-scope="scope">
                  <i class="el-icon-check" v-if="scope.row.https"></i>
                </template>
              </el-table-column>
              <el-table-column prop="anonymous" label="ANONYMOUS" width="130">
                <template slot-scope="scope">
                  <i class="el-icon-check" v-if="scope.row.anonymous"></i>
                </template>
              </el-table-column>
              <el-table-column prop="location" label="LOCATION" width="200"></el-table-column>
              <el-table-column prop="delay" label="DELAY" width="110"></el-table-column>
              <el-table-column prop="validate_time" label="VALIDATE TIME" width="390"></el-table-column>
            </el-table>
          </template>
        </div>
        <div class="block">
          <el-pagination layout="total, prev, pager, next" :total="total" :page-size="page_size" @current-change="handleCurrentChange"></el-pagination>
        </div>
      </el-col>
    </el-row>
  </div>

</div>

<div id="test">
  <span v-text="proxiesData"></span>
</div>

</body>

<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script>

<script src="/static/js/app.js"></script>

<script>
</script>

</html>